-- Insert real Swiss hospitals in Ticino region
-- Using 'hospital' and 'institute' as allowed by org_type CHECK constraint
INSERT INTO organizations (
  id, name, org_type, address, city, province, region, country,
  email, phone, website, vat_number, notes, latitude, longitude, is_active, created_at, updated_at
) VALUES
-- Ospedale Regionale di Lugano - Civico
(
  gen_random_uuid(),
  'Ospedale Regionale di Lugano - Civico',
  'hospital',
  'Via Tesserete 46',
  'Lugano',
  'Lugano',
  'Ticino',
  'Svizzera',
  'info@eoc.ch',
  '+41 91 811 61 11',
  'https://www.eoc.ch',
  'CHE-123.456.789',
  'Ospedale pubblico principale del Canton Ticino',
  46.0073,
  8.9540,
  true,
  NOW(),
  NOW()
),
-- Clinica Luganese Moncucco (institute type)
(
  gen_random_uuid(),
  'Clinica Luganese Moncucco',
  'institute',
  'Via Moncucco 10',
  'Lugano',
  'Lugano',
  'Ticino',
  'Svizzera',
  'info@moncucco.ch',
  '+41 91 960 81 11',
  'https://www.moncucco.ch',
  'CHE-234.567.890',
  'Clinica privata con servizi di radiologia avanzata',
  46.0037,
  8.9467,
  true,
  NOW(),
  NOW()
),
-- Cardiocentro Ticino (institute type)
(
  gen_random_uuid(),
  'Cardiocentro Ticino',
  'institute',
  'Via Tesserete 48',
  'Lugano',
  'Lugano',
  'Ticino',
  'Svizzera',
  'info@cardiocentro.org',
  '+41 91 805 31 11',
  'https://www.cardiocentro.org',
  'CHE-345.678.901',
  'Centro specializzato in cardiologia e diagnostica per immagini',
  46.0075,
  8.9545,
  true,
  NOW(),
  NOW()
),
-- Ospedale Regionale di Mendrisio - Beata Vergine
(
  gen_random_uuid(),
  'Ospedale Regionale di Mendrisio',
  'hospital',
  'Via Alfonso Turconi 23',
  'Mendrisio',
  'Mendrisio',
  'Ticino',
  'Svizzera',
  'info.mendrisio@eoc.ch',
  '+41 91 811 31 11',
  'https://www.eoc.ch',
  'CHE-456.789.012',
  'Ospedale regionale della zona sud del Ticino',
  45.8712,
  8.9857,
  true,
  NOW(),
  NOW()
),
-- Clinica Sant'Anna (institute type)
(
  gen_random_uuid(),
  'Clinica Sant''Anna',
  'institute',
  'Via Sant''Anna 1',
  'Sorengo',
  'Lugano',
  'Ticino',
  'Svizzera',
  'info@clinicasantanna.ch',
  '+41 91 985 11 11',
  'https://www.clinicasantanna.ch',
  'CHE-567.890.123',
  'Clinica privata multidisciplinare con imaging avanzato',
  45.9924,
  8.9395,
  true,
  NOW(),
  NOW()
),
-- Ospedale Regionale di Bellinzona
(
  gen_random_uuid(),
  'Ospedale Regionale di Bellinzona',
  'hospital',
  'Viale Officina 3',
  'Bellinzona',
  'Bellinzona',
  'Ticino',
  'Svizzera',
  'info.bellinzona@eoc.ch',
  '+41 91 811 91 11',
  'https://www.eoc.ch',
  'CHE-678.901.234',
  'Ospedale regionale con centro oncologico',
  46.1955,
  9.0237,
  true,
  NOW(),
  NOW()
),
-- Ospedale Regionale di Locarno
(
  gen_random_uuid(),
  'Ospedale Regionale di Locarno',
  'hospital',
  'Via all''Ospedale 1',
  'Locarno',
  'Locarno',
  'Ticino',
  'Svizzera',
  'info.locarno@eoc.ch',
  '+41 91 811 41 11',
  'https://www.eoc.ch',
  'CHE-789.012.345',
  'Ospedale regionale del Locarnese',
  46.1692,
  8.7922,
  true,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;
